### ISSUE TITLE
Add the xk6 label to the repository

### ISSUE THREAD

**Issue by simonaronsson** [ForgottenWorld/xk6-minecraft#1]
Hi,

We're so excited to see that you've built an xk6 extension for reliability testing Minecraft servers. If you don't mind, it would be great if you could add the `xk6` label to the repository so that it is visible for other users of xk6 as well when browsing https://github.com/topic/xk6.

Thanks a bunch,
Simme & the k6 team

**Comment by enduvar** [comment]
Hello Simme,

The project is still in a very early stage.
We talked about this and we decided to wait, once the project is mature enough to use we will surely add the label.

Thanks for your interest in our work.
